/**
 * Migration: Populate propOverrides with configSchema defaults for all widget elements
 * that have sparse propOverrides (only token or empty).
 * 
 * This ensures:
 * 1. The editor inspector shows correct values
 * 2. The snapshot has full visual config
 * 3. Future saves preserve the full config
 * 
 * Safe to run multiple times — only updates widgets where propOverrides is sparse.
 */

import db from '/var/www/scraplet/scraplet-dashboard/db.js';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load widget defaults (generated by extract_defaults.mjs)
const widgetDefaults = JSON.parse(
  readFileSync(path.join(__dirname, 'src/widgets/widgetDefaults.json'), 'utf8')
);

console.log('Loaded defaults for widgets:', Object.keys(widgetDefaults).join(', '));

// Fetch all overlays
const { rows: overlays } = await db.query(
  'SELECT id, public_id, user_id, config_json FROM overlays WHERE config_json IS NOT NULL'
);

console.log(`Processing ${overlays.length} overlays...`);

let totalUpdated = 0;
let totalSkipped = 0;

for (const overlay of overlays) {
  const config = overlay.config_json;
  if (!config?.elements?.length) continue;

  let changed = false;
  const updatedElements = config.elements.map(el => {
    if (el.type !== 'widget') return el;
    
    const widgetId = el.widgetId;
    const defaults = widgetDefaults[widgetId];
    if (!defaults || Object.keys(defaults).length === 0) return el;

    const currentProps = el.propOverrides || {};
    const nonTokenKeys = Object.keys(currentProps).filter(k => k !== 'token');
    
    // Only migrate if propOverrides is sparse (0 or 1 non-token keys)
    // If the user has already configured things, don't overwrite
    if (nonTokenKeys.length > 2) {
      totalSkipped++;
      return el; // Already has config, skip
    }

    // Merge: defaults → current propOverrides (current takes precedence)
    const merged = {
      ...defaults,
      ...currentProps, // user's existing overrides win
    };

    // Check if anything actually changed
    const mergedKeys = Object.keys(merged);
    const currentKeys = Object.keys(currentProps);
    if (mergedKeys.length === currentKeys.length && 
        mergedKeys.every(k => JSON.stringify(merged[k]) === JSON.stringify(currentProps[k]))) {
      totalSkipped++;
      return el;
    }

    changed = true;
    totalUpdated++;
    console.log(`  Overlay ${overlay.public_id}: updating ${widgetId} (${el.id.slice(0,20)}) - added ${mergedKeys.length - currentKeys.length} keys`);
    
    return { ...el, propOverrides: merged };
  });

  if (changed) {
    await db.query(
      'UPDATE overlays SET config_json = $1 WHERE id = $2',
      [{ ...config, elements: updatedElements }, overlay.id]
    );
  }
}

console.log(`\nMigration complete:`);
console.log(`  Updated: ${totalUpdated} widget elements`);
console.log(`  Skipped: ${totalSkipped} widget elements (already configured or no defaults)`);

process.exit(0);
