// src/widgets/allWidgets.ts
// Registers all overlay widgets in the WIDGET_REGISTRY.
// Import this from the overlay editor and runtime entry points.

import { registerWidget } from '../shared/widgetRegistry.js';

registerWidget({
  id: 'chat-overlay',
  name: 'Chat Overlay',
  schemaVersion: 2,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'chat-overlay',
    category:    'display',
    version:     '2.0.0',
    displayName: 'Chat Overlay',
    description: 'Displays live chat messages from Kick, YouTube, and Twitch. Fully customisable with bubble styles, avatars, and platform icons.',
    icon:        'monitor',
    dataContract: {
      sseEventType: 'chat_message',
      fields: [
        { key: 'username', label: 'Username',     type: 'string', fallback: '' },
        { key: 'message',  label: 'Message',      type: 'string', fallback: '' },
        { key: 'platform', label: 'Platform',     type: 'string', fallback: 'kick' },
        { key: 'avatar',   label: 'Avatar URL',   type: 'string', fallback: '' },
        { key: 'color',    label: 'Name Colour',  type: 'string', fallback: '' },
      ],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/chat-overlay.js',
    configSchema: [
      // Typography
      { key: 'fontFamily', type: 'select', label: 'Font', default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Source Code Pro','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',      type: 'number',  label: 'Font size (px)',        default: 16 },
      { key: 'lineHeight',      type: 'number',  label: 'Line height',           default: 1.4 },
      { key: 'messageGapPx',    type: 'number',  label: 'Gap between messages (px)', default: 6 },
      // Colours
      { key: 'nameColorMode', type: 'select', label: 'Name colour mode', default: 'custom', options: ['custom', 'platform', 'user'] },
      { key: 'nameColor', type: 'color', label: 'Name colour (custom)', default: '#a5b4fc', showWhen: { key: 'nameColorMode', value: 'custom' } },
      { key: 'messageColor',    type: 'color',   label: 'Message colour',        default: '#ffffff' },
      // Display options
      { key: 'showAvatars',     type: 'boolean', label: 'Show avatars',          default: false },
      { key: 'showBadges',      type: 'boolean', label: 'Show badges',           default: true },
      { key: 'gradientNames',   type: 'boolean', label: 'Gradient name colours', default: false },
      { key: 'showPlatformIcon',type: 'boolean', label: 'Show platform icon',    default: true },
      { key: 'shadow',          type: 'boolean', label: 'Text shadow',           default: true },
      { key: 'animateIn',       type: 'boolean', label: 'Animate messages in',   default: true },
      { key: 'stripEmotes',     type: 'boolean', label: 'Strip emote codes',      default: false },
      // Bubble style
      { key: 'bubbleEnabled',   type: 'boolean', label: 'Message bubbles',       default: false },
      { key: 'bubbleRadiusPx',  type: 'number',  label: 'Bubble corner radius',  default: 8 },
      { key: 'bubbleBg',        type: 'color',   label: 'Bubble background',     default: 'rgba(0,0,0,0.4)' },
      { key: 'bubbleBorder',    type: 'color',   label: 'Bubble border',         default: 'transparent' },
      // Limits
      { key: 'limitsMaxMessages', type: 'number', label: 'Max messages shown',   default: 20 },
      { key: 'limitsFadeMs',    type: 'number',  label: 'Fade out after (ms, 0=never)', default: 0 },
      // Visual effects
      { key: 'glowEnabled',     type: 'boolean', label: 'Name glow effect',      default: false },
      { key: 'glowColor',       type: 'color',   label: 'Glow colour',           default: '#a5b4fc' },
      { key: 'glowBlur',        type: 'number',  label: 'Glow blur (px)',        default: 8 },
      { key: 'depthEnabled',    type: 'boolean', label: 'Depth/3D effect',       default: false },
      { key: 'depthOffset',     type: 'number',  label: 'Depth offset (px)',     default: 2 },
      { key: 'depthColor',      type: 'color',   label: 'Depth colour',          default: 'rgba(0,0,0,0.5)' },
      // Platform filters
      { key: 'enableKick',      type: 'boolean', label: 'Show Kick chat',        default: true },
      { key: 'enableYoutube',   type: 'boolean', label: 'Show YouTube chat',     default: true },
      { key: 'enableTwitch',    type: 'boolean', label: 'Show Twitch chat',      default: true },
    ],
    defaultProps: {
      token: '',
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSizePx: 16, lineHeight: 1.4, messageGapPx: 6,
      nameColor: '#a5b4fc', messageColor: '#ffffff',
      showAvatars: false, showPlatformIcon: true, shadow: true, animateIn: true,
      bubbleEnabled: false, bubbleRadiusPx: 8, bubbleBg: 'rgba(0,0,0,0.4)', bubbleBorder: 'transparent',
      limitsMaxMessages: 20, limitsFadeMs: 0,
      enableKick: true, enableYoutube: true, enableTwitch: true,
    },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'alert-box-widget',
  name: 'Alert Box',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'alert-box-widget',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Alert Box',
    description: 'Shows animated alerts for follows, subs, donations, and raids.',
    icon:        'monitor',
    dataContract: {
      sseEventType: 'follow',
      fields: [
        { key: 'username', label: 'Username', type: 'string', fallback: '' },
        { key: 'message',  label: 'Message',  type: 'string', fallback: '' },
        { key: 'type',     label: 'Event Type', type: 'string', fallback: '' },
      ],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/alert-box-widget.js',
    configSchema: [
      // Global
      { key: 'fontFamily',    type: 'select', label: 'Font', default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',    type: 'number', label: 'Font size (px)', default: 20 },
      { key: 'textColor',     type: 'color',  label: 'Text colour',    default: '#ffffff' },
      { key: 'masterVolume',  type: 'number', label: 'Master volume',  default: 0.8 },
      { key: 'layoutMode',   type: 'select', label: 'Layout mode', default: 'classic', options: ['classic', 'media-fill'] },
      // Per-event config — rendered by alertConfig inspector
      { key: 'alertTypes', type: 'alertConfig', label: 'Alert Events', default: {} },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'sub-counter',
  name: 'Sub Counter',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'sub-counter',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Sub Counter',
    description: 'Shows subscriber count with an optional goal progress bar.',
    icon:        'monitor',
    dataContract: {
      sseEventType: null,
      fields: [],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/sub-counter.js',
    configSchema: [
      // Display
      { key: 'displayMode',   type: 'select',  label: 'Display mode',      default: 'bar',   options: ['bar','ring','counter'] },
      { key: 'label',         type: 'text',    label: 'Label',             default: 'Sub Goal' },
      { key: 'fontFamily',    type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',    type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'textColor',     type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'fillColor',     type: 'color',   label: 'Bar fill colour',   default: '#6366f1' },
      { key: 'fillColor2',    type: 'color',   label: 'Bar fill gradient', default: '' },
      { key: 'trackColor',    type: 'color',   label: 'Bar track colour',  default: 'rgba(255,255,255,0.1)' },
      { key: 'bgColor',       type: 'color',   label: 'Background',        default: 'transparent' },
      // Goal
      { key: 'goal',          type: 'number',  label: 'Goal',              default: 100 },
      { key: 'startAt',       type: 'number',  label: 'Starting count',    default: 0 },
      { key: 'overfill',      type: 'boolean', label: 'Overfill bar',      default: true },
      { key: 'trackPoints',   type: 'boolean', label: 'Track sub points (tier-weighted)', default: false },
      { key: 'endDate',       type: 'text',    label: 'End date (ISO)',    default: '' },
      // Numbers
      { key: 'showNumbers',   type: 'boolean', label: 'Show numbers',      default: true },
      { key: 'showPercent',   type: 'boolean', label: 'Show percentage',   default: false },
      { key: 'showBreakdown', type: 'boolean', label: 'Show platform breakdown', default: false },
      // Milestone
      { key: 'milestoneAnim', type: 'select',  label: 'Milestone animation', default: 'pulse', options: ['pulse','shake','none'] },
      // Bar style
      { key: 'barHeight',     type: 'number',  label: 'Bar height (px)',   default: 12, showWhen: { key: 'displayMode', value: 'bar' } },
      { key: 'barRadius',     type: 'number',  label: 'Bar corner radius', default: 999, showWhen: { key: 'displayMode', value: 'bar' } },
      { key: 'barGlow',       type: 'boolean', label: 'Bar glow effect',   default: false, showWhen: { key: 'displayMode', value: 'bar' } },
      // Ring style
      { key: 'ringSize',      type: 'number',  label: 'Ring size (px)',    default: 120, showWhen: { key: 'displayMode', value: 'ring' } },
      { key: 'ringStroke',    type: 'number',  label: 'Ring stroke width', default: 10,  showWhen: { key: 'displayMode', value: 'ring' } },
      { key: 'ringGlow',      type: 'boolean', label: 'Ring glow effect',  default: false, showWhen: { key: 'displayMode', value: 'ring' } },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'event-console-widget',
  name: 'Event Console',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'event-console-widget',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Event Console',
    description: 'Shows a scrolling log of stream events — follows, subs, donations, chat.',
    icon:        'monitor',
    dataContract: {
      sseEventType: 'follow',
      fields: [
        { key: 'username', label: 'Username', type: 'string', fallback: '' },
        { key: 'message',  label: 'Message',  type: 'string', fallback: '' },
        { key: 'type',     label: 'Event Type', type: 'string', fallback: '' },
      ],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/event-console-widget.js',
    configSchema: [
      { key: 'newestTop',     type: 'boolean', label: 'Newest at top',        default: true },
      { key: 'maxEvents',     type: 'number',  label: 'Max events shown',     default: 12 },
      { key: 'expireSec',     type: 'number',  label: 'Auto-expire after (s, 0=never)', default: 0 },
      { key: 'entryAnim',     type: 'select',  label: 'Entry animation',      default: 'slide-left', options: ['slide-left','slide-right','fade','scale'] },
      { key: 'fontFamily',    type: 'select',  label: 'Font',                 default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',    type: 'number',  label: 'Font size (px)',       default: 14 },
      { key: 'textColor',     type: 'color',   label: 'Text colour',          default: '#e2e8f0' },
      { key: 'rowBg',         type: 'color',   label: 'Row background',       default: 'rgba(0,0,0,0.4)' },
      { key: 'rowBgAlt',      type: 'color',   label: 'Alternating row bg',   default: '' },
      { key: 'containerBg',   type: 'color',   label: 'Container background', default: 'transparent' },
      { key: 'borderRadius',  type: 'number',  label: 'Border radius (px)',   default: 8 },
      { key: 'rowPadding',    type: 'number',  label: 'Row padding (px)',     default: 6 },
      { key: 'accentWidth',   type: 'number',  label: 'Accent bar width (px)',default: 3 },
      { key: 'showTimestamp', type: 'boolean', label: 'Show timestamp',       default: false },
      { key: 'showAvatar',    type: 'boolean', label: 'Show avatars',         default: false },
      { key: 'showPlatform',  type: 'boolean', label: 'Show platform icon',   default: true },
      { key: 'eventTypes',    type: 'alertConfig', label: 'Event Types',      default: {} },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'raffle',
  name: 'Raffle',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'raffle',
    category:    'interactive',
    version:     '1.0.0',
    displayName: 'Raffle',
    description: 'Live raffle widget — viewers enter via chat command, winner drawn on screen.',
    icon:        'monitor',
    dataContract: {
      sseEventType: 'raffle_update',
      fields: [
        { key: 'username', label: 'Username', type: 'string', fallback: '' },
        { key: 'message',  label: 'Message',  type: 'string', fallback: '' },
        { key: 'type',     label: 'Event Type', type: 'string', fallback: '' },
      ],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/raffle.js',
    configSchema: [
      // Visual
      { key: 'fontFamily',   type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',   type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'textColor',    type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor',  type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'winnerColor',  type: 'color',   label: 'Winner colour',     default: '#fbbf24' },
      { key: 'bgColor',      type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.85)' },
      { key: 'borderRadius', type: 'number',  label: 'Border radius (px)',default: 16 },
      // Animation preference (empty = use server value)
      { key: 'prefAnim',     type: 'select',  label: 'Animation override',default: '', options: ['','wheel','slot','scramble'] },
      // Toggles
      { key: 'showStatus',   type: 'boolean', label: 'Show status dot',   default: true },
      { key: 'showCount',    type: 'boolean', label: 'Show entry count',  default: true },
      { key: 'showJoinCmd',  type: 'boolean', label: 'Show join command', default: true },
      { key: 'joinCommand',  type: 'text',    label: 'Join command',      default: '!join' },
      { key: 'autoDismissSec', type: 'number',  label: 'Auto-dismiss after winner (s, 0=never)', default: 10 },
      { key: 'subWeight',      type: 'number',  label: 'Subscriber entry weight (1=normal, 2=double chance)', default: 1 },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});


registerWidget({
  id: 'random-number',
  name: 'Random Number',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'random-number',
    category:    'interactive',
    version:     '1.0.0',
    displayName: 'Random Number Generator',
    description: 'Wheel spin, number picker, or coin flip. Trigger via chat command or dashboard.',
    icon:        'monitor',
    dataContract: { sseEventType: 'chat_message', fields: [{ key: 'message', label: 'Message', type: 'string', fallback: '' }] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/random-number.js',
    configSchema: [
      { key: 'mode',        type: 'select',  label: 'Mode',              default: 'number', options: ['number','wheel','coin'] },
      { key: 'minVal',      type: 'number',  label: 'Min value',         default: 1,   showWhen: { key: 'mode', value: 'number' } },
      { key: 'maxVal',      type: 'number',  label: 'Max value',         default: 100, showWhen: { key: 'mode', value: 'number' } },
      { key: 'wheelItems',  type: 'text',    label: 'Wheel items (comma-separated)', default: 'Option 1,Option 2,Option 3,Option 4,Option 5', showWhen: { key: 'mode', value: 'wheel' } },
      { key: 'triggerCmd',  type: 'text',    label: 'Chat trigger command', default: '!roll' },
      { key: 'cmdPermission', type: 'select', label: 'Command permission', default: 'all', options: ['all','moderator','broadcaster'] },
      { key: 'autoHideStartup', type: 'boolean', label: 'Auto-hide on startup', default: false },
      { key: 'autoHideStartupDelay', type: 'number', label: 'Startup hide delay (ms)', default: 1000, showWhen: { key: 'autoHideStartup', value: true } },
      { key: 'autoHideClose', type: 'boolean', label: 'Auto-hide after result', default: false },
      { key: 'autoHideCloseDelay', type: 'number', label: 'Close hide delay (ms)', default: 1000, showWhen: { key: 'autoHideClose', value: true } },
      { key: 'fontFamily',  type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',  type: 'number',  label: 'Font size (px)',    default: 64 },
      { key: 'textColor',   type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor', type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'bgColor',     type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.85)' },
      { key: 'borderRadius',type: 'number',  label: 'Border radius (px)',default: 16 },
      { key: 'showTitle',   type: 'boolean', label: 'Show title',        default: true },
      { key: 'titleText',   type: 'text',    label: 'Custom title (leave empty for default)', default: '', showWhen: { key: 'showTitle', value: true } },
      { key: 'showCmd',     type: 'boolean', label: 'Show trigger hint',  default: true },
      { key: 'showHistory', type: 'boolean', label: 'Show result history', default: false },
      { key: 'historyCount', type: 'number', label: 'History items to show', default: 10, showWhen: { key: 'showHistory', value: true } },
      { key: 'autoDismiss', type: 'number',  label: 'Auto-dismiss (ms, 0=never)', default: 5000 },
      // Wheel nominations
      { key: 'chatNominate',      type: 'boolean', label: 'Allow viewer nominations (wheel)', default: false, showWhen: { key: 'mode', value: 'wheel' } },
      { key: 'nominateCmd',       type: 'text',    label: 'Nominate command',   default: '!add',        showWhen: { key: 'chatNominate', value: true } },
      { key: 'nominatePermission',type: 'select',  label: 'Who can nominate',   default: 'all', options: ['all','moderator','broadcaster'], showWhen: { key: 'chatNominate', value: true } },
      { key: 'maxNominations',    type: 'number',  label: 'Max nominations',    default: 20,            showWhen: { key: 'chatNominate', value: true } },
      { key: 'showNominationCount', type: 'boolean', label: 'Show nomination list', default: true,      showWhen: { key: 'chatNominate', value: true } },
      { key: 'clearAfterSpin',    type: 'boolean', label: 'Clear nominations after spin', default: false, showWhen: { key: 'chatNominate', value: true } },
      { key: 'setOptionsCmd',     type: 'text',    label: 'Set options command (mod)', default: '!setoptions', showWhen: { key: 'mode', value: 'wheel' } },
      { key: 'clearCmd',          type: 'text',    label: 'Clear wheel command (mod)', default: '!clearwheel', showWhen: { key: 'mode', value: 'wheel' } },
    ],
    defaultProps: {},
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'emote-wall',
  name: 'Emote Wall',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'emote-wall',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Emote Wall',
    description: 'Chat emotes float across the screen as viewers send them.',
    icon:        'monitor',
    dataContract: { sseEventType: 'chat_message', fields: [{ key: 'message', label: 'Message', type: 'string', fallback: '' }] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/emote-wall.js',
    configSchema: [
      { key: 'emoteSize',   type: 'number',  label: 'Emote size (px)',   default: 48 },
      { key: 'speed',       type: 'number',  label: 'Float speed (s)',   default: 4 },
      { key: 'maxOnScreen', type: 'number',  label: 'Max on screen',     default: 50 },
      { key: 'direction',   type: 'select',  label: 'Direction',         default: 'up', options: ['up','right','left','random'] },
      { key: 'showNames',   type: 'boolean', label: 'Show emote names',  default: false },
      { key: 'bgColor',     type: 'color',   label: 'Background',        default: 'transparent' },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'emote-counter',
  name: 'Emote Counter',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'emote-counter',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Emote Counter',
    description: 'Counts specific emotes used in chat over a rolling time window.',
    icon:        'monitor',
    dataContract: { sseEventType: 'chat_message', fields: [{ key: 'message', label: 'Message', type: 'string', fallback: '' }] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/emote-counter.js',
    configSchema: [
      { key: 'watchEmotes', type: 'text',    label: 'Emotes to track (comma-separated)', default: 'PogChamp,KEKW,LUL,Pog' },
      { key: 'windowSec',   type: 'number',  label: 'Rolling window (s, 0=all time)', default: 30 },
      { key: 'maxDisplay',  type: 'number',  label: 'Top N to show',     default: 5 },
      { key: 'title',       type: 'text',    label: 'Title',             default: 'Emote Counter' },
      { key: 'fontFamily',  type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',  type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'textColor',   type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor', type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'bgColor',     type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.75)' },
      { key: 'borderRadius',type: 'number',  label: 'Border radius (px)',default: 12 },
      { key: 'showBar',     type: 'boolean', label: 'Show bar chart',    default: true },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'top-donators',
  name: 'Top Donators',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'top-donators',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Top Donators',
    description: 'Live leaderboard of top donors this session.',
    icon:        'monitor',
    dataContract: { sseEventType: 'donation', fields: [{ key: 'username', label: 'Username', type: 'string', fallback: '' }, { key: 'amount', label: 'Amount', type: 'number', fallback: 0 }] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/top-donators.js',
    configSchema: [
      { key: 'maxEntries',  type: 'number',  label: 'Max entries',       default: 5 },
      { key: 'title',       type: 'text',    label: 'Title',             default: 'Top Donators' },
      { key: 'currency',    type: 'text',    label: 'Currency symbol',   default: '$' },
      { key: 'fontFamily',  type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',  type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'textColor',   type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor', type: 'color',   label: 'Amount colour',     default: '#fbbf24' },
      { key: 'bgColor',     type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.75)' },
      { key: 'borderRadius',type: 'number',  label: 'Border radius (px)',default: 12 },
      { key: 'showRank',    type: 'boolean', label: 'Show rank numbers', default: true },
      { key: 'showBar',     type: 'boolean', label: 'Show bar chart',    default: true },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'sound-visualizer',
  name: 'Sound Visualizer',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'sound-visualizer',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Sound Visualizer',
    description: 'Audio visualizer with bars, wave, pips, and mirror modes.',
    icon:        'monitor',
    dataContract: { sseEventType: null, fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/sound-visualizer.js',
    configSchema: [
      { key: 'mode',        type: 'select',  label: 'Mode',              default: 'bars', options: ['bars','wave','pips','mirror-bars'] },
      { key: 'barCount',    type: 'number',  label: 'Bar / point count', default: 32 },
      { key: 'color1',      type: 'color',   label: 'Colour 1',          default: '#6366f1' },
      { key: 'color2',      type: 'color',   label: 'Colour 2 (gradient end)', default: '#a855f7' },
      { key: 'bgColor',     type: 'color',   label: 'Background',        default: 'transparent' },
      { key: 'barRadius',   type: 'number',  label: 'Bar corner radius', default: 4 },
      { key: 'barGap',      type: 'number',  label: 'Bar gap (px)',      default: 3 },
      { key: 'sensitivity', type: 'number',  label: 'Sensitivity',       default: 1.5 },
      { key: 'smoothing',   type: 'number',  label: 'Smoothing (0-1)',   default: 0.8 },
      { key: 'minHeight',   type: 'number',  label: 'Min bar height (px)', default: 4 },
      { key: 'mirrorH',     type: 'boolean', label: 'Mirror horizontally', default: false },
    ],
    defaultProps: {},
    previewImageUrl: null,
  },
});


registerWidget({
  id: 'poll',
  name: 'Poll',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'poll',
    category:    'interactive',
    version:     '1.0.0',
    displayName: 'Poll / Vote',
    description: 'Live poll with real-time vote bars. Integrates with Kick native polls and chat commands.',
    icon:        'monitor',
    dataContract: { sseEventType: 'poll.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/poll.js',
    configSchema: [
      { key: 'fontFamily',    type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',    type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'textColor',     type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'bgColor',       type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.85)' },
      { key: 'accentColor',   type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'borderRadius',  type: 'number',  label: 'Border radius (px)',default: 12 },
      { key: 'showTimer',     type: 'boolean', label: 'Show countdown timer', default: true },
      { key: 'showVoteCount', type: 'boolean', label: 'Show vote counts',  default: true },
      { key: 'showPercent',   type: 'boolean', label: 'Show percentages',  default: true },
      { key: 'animateBars',   type: 'boolean', label: 'Animate bars',      default: true },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'countdown',
  name: 'Countdown',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'countdown',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Countdown Timer',
    description: 'Count down to a specific date/time or from a set duration.',
    icon:        'monitor',
    dataContract: { sseEventType: null, fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/countdown.js',
    configSchema: [
      { key: 'mode',            type: 'select',  label: 'Mode',              default: 'datetime', options: ['datetime','duration'] },
      { key: 'targetDatetime',  type: 'text',    label: 'Target date/time (ISO)', default: '' },
      { key: 'durationSec',     type: 'number',  label: 'Duration (seconds)', default: 300 },
      { key: 'layout',          type: 'select',  label: 'Layout',            default: 'blocks', options: ['blocks','inline'] },
      { key: 'showDays',        type: 'boolean', label: 'Show days',         default: true },
      { key: 'showHours',       type: 'boolean', label: 'Show hours',        default: true },
      { key: 'showMinutes',     type: 'boolean', label: 'Show minutes',      default: true },
      { key: 'showSeconds',     type: 'boolean', label: 'Show seconds',      default: true },
      { key: 'showLabels',      type: 'boolean', label: 'Show unit labels',  default: true },
      { key: 'endMessage',      type: 'text',    label: 'End message',       default: 'LIVE NOW! 🔴' },
      { key: 'urgentThreshold', type: 'number',  label: 'Urgent below (s)',  default: 60 },
      { key: 'showProgressBar', type: 'boolean', label: 'Show progress bar', default: false },
      { key: 'fontFamily',      type: 'select',  label: 'Font',              default: 'Orbitron', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Orbitron','Audiowide','Rajdhani'] },
      { key: 'fontSizePx',      type: 'number',  label: 'Font size (px)',    default: 48 },
      { key: 'textColor',       type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor',     type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'urgentColor',     type: 'color',   label: 'Urgent colour',     default: '#ef4444' },
      { key: 'bgColor',         type: 'color',   label: 'Background',        default: 'transparent' },
      { key: 'separator',       type: 'text',    label: 'Separator',         default: ':' },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'top-supporters',
  name: 'Top Supporters',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'top-supporters',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Top Supporters',
    description: 'Live leaderboard of top subs, tippers, and supporters this session.',
    icon:        'monitor',
    dataContract: { sseEventType: 'subs.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/top-supporters.js',
    configSchema: [
      { key: 'metric',      type: 'select',  label: 'Rank by',           default: 'combined', options: ['combined','subs','tips'] },
      { key: 'layout',      type: 'select',  label: 'Layout',            default: 'list', options: ['list','podium'] },
      { key: 'maxEntries',  type: 'number',  label: 'Max entries',       default: 5 },
      { key: 'title',       type: 'text',    label: 'Title',             default: 'Top Supporters' },
      { key: 'showPlatform',type: 'boolean', label: 'Show platform icon',default: true },
      { key: 'showPoints',  type: 'boolean', label: 'Show points',       default: true },
      { key: 'fontFamily',  type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',  type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'textColor',   type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor', type: 'color',   label: 'Accent colour',     default: '#fbbf24' },
      { key: 'bgColor',     type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.75)' },
      { key: 'borderRadius',type: 'number',  label: 'Border radius (px)',default: 12 },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'media-queue',
  name: 'Media Queue',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'media-queue',
    category:    'interactive',
    version:     '1.0.0',
    displayName: 'Media Request Queue',
    description: 'Song/video request queue. Viewers request via chat, streamer manages from dashboard.',
    icon:        'monitor',
    dataContract: { sseEventType: 'queue.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/media-queue.js',
    configSchema: [
      { key: 'showNowPlaying', type: 'boolean', label: 'Show now playing',  default: true },
      { key: 'maxQueueItems',  type: 'number',  label: 'Queue items shown', default: 4 },
      { key: 'showRequester',  type: 'boolean', label: 'Show requester',    default: true },
      { key: 'showVotes',      type: 'boolean', label: 'Show vote count',   default: true },
      { key: 'title',          type: 'text',    label: 'Title',             default: 'Request Queue' },
      { key: 'emptyMessage',   type: 'text',    label: 'Empty queue message', default: 'Use !sr to request' },
      { key: 'fontFamily',     type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',     type: 'number',  label: 'Font size (px)',    default: 16 },
      { key: 'textColor',      type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor',    type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'nowPlayingColor',type: 'color',   label: 'Now playing colour',default: '#22c55e' },
      { key: 'bgColor',        type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.85)' },
      { key: 'borderRadius',   type: 'number',  label: 'Border radius (px)',default: 12 },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'viewer-count',
  name: 'Viewer Count',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'viewer-count',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Viewer Count',
    description: 'Live viewer count with per-platform breakdown and peak tracking.',
    icon:        'monitor',
    dataContract: { sseEventType: 'viewer.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/viewer-count.js',
    configSchema: [
      { key: 'layout',      type: 'select',  label: 'Layout',            default: 'vertical', options: ['vertical','horizontal','compact'] },
      { key: 'showKick',    type: 'boolean', label: 'Show Kick',         default: true },
      { key: 'showYoutube', type: 'boolean', label: 'Show YouTube',      default: true },
      { key: 'showTwitch',  type: 'boolean', label: 'Show Twitch',       default: true },
      { key: 'showTotal',   type: 'boolean', label: 'Show total',        default: true },
      { key: 'showPeak',    type: 'boolean', label: 'Show peak viewers', default: true },
      { key: 'showPlatformBreakdown', type: 'boolean', label: 'Show platform breakdown', default: true },
      { key: 'title',       type: 'text',    label: 'Title',             default: 'Viewers' },
      { key: 'fontFamily',  type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',  type: 'number',  label: 'Font size (px)',    default: 48 },
      { key: 'textColor',   type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor', type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'bgColor',     type: 'color',   label: 'Background',        default: 'transparent' },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'ticker',
  name: 'Ticker',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'ticker',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Scrolling Ticker',
    description: 'Infinite scrolling text ticker for announcements, sponsors, and social handles.',
    icon:        'monitor',
    dataContract: { sseEventType: null, fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/ticker.js',
    configSchema: [
      { key: 'items',        type: 'text',    label: 'Items (pipe-separated)', default: 'Follow us on Kick!|Subscribe for more!|Use code SCRAPLET for 10% off!' },
      { key: 'speed',        type: 'number',  label: 'Speed (px/sec)',    default: 80 },
      { key: 'direction',    type: 'select',  label: 'Direction',         default: 'left', options: ['left','right'] },
      { key: 'prefix',       type: 'text',    label: 'Prefix label',      default: '📢 LIVE' },
      { key: 'separator',    type: 'text',    label: 'Item separator',    default: '•' },
      { key: 'pauseOnHover', type: 'boolean', label: 'Pause on hover',    default: false },
      { key: 'edgeFade',     type: 'boolean', label: 'Edge fade effect',  default: true },
      { key: 'fontFamily',   type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',   type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'textColor',    type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor',  type: 'color',   label: 'Separator colour',  default: '#6366f1' },
      { key: 'bgColor',      type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.75)' },
    ],
    defaultProps: {},
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'hype-train',
  name: 'Hype Train',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'hype-train',
    category:    'interactive',
    version:     '1.0.0',
    displayName: 'Hype Train',
    description: 'Animated hype train that levels up with subs, tips, and donations. Scrapbot narrates the ride.',
    icon:        'monitor',
    dataContract: { sseEventType: 'hype.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/hype-train.js',
    configSchema: [
      { key: 'difficulty',    type: 'select',  label: 'Difficulty',        default: 'alright', options: ['easy','alright','hard','insane'] },
      { key: 'timerSec',      type: 'number',  label: 'Timer per contribution (s)', default: 60 },
      { key: 'tipUnit',       type: 'number',  label: 'Tip $ per point',   default: 5 },
      { key: 'narrate',       type: 'boolean', label: 'Scrapbot narration', default: true },
      { key: 'showConductor', type: 'boolean', label: 'Show conductor',    default: true },
      { key: 'showLevel',     type: 'boolean', label: 'Show level',        default: true },
      { key: 'showTimer',     type: 'boolean', label: 'Show timer bar',    default: true },
      { key: 'showTimerText', type: 'boolean', label: 'Show timer countdown', default: true },
      { key: 'trainColor',    type: 'color',   label: 'Train colour',      default: '#1e293b' },
      { key: 'accentColor',   type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'wheelColor',    type: 'color',   label: 'Wheel colour',      default: '#475569' },
      { key: 'barColor',      type: 'color',   label: 'Timer bar colour',  default: '#6366f1' },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'subathon-timer',
  name: 'Subathon Timer',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'subathon-timer',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Subathon Timer',
    description: 'Countdown timer that gains time from subs, tips, and donations.',
    icon:        'monitor',
    dataContract: { sseEventType: 'subs.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/subathon-timer.js',
    configSchema: [
      { key: 'initialMinutes', type: 'number',  label: 'Starting time (min)', default: 60 },
      { key: 'subMinutes',     type: 'number',  label: 'Minutes per sub',     default: 5 },
      { key: 'tipMinutes',     type: 'number',  label: 'Minutes per $1 tip',  default: 1 },
      { key: 'maxHours',       type: 'number',  label: 'Max time cap (hours, 0=none)', default: 0 },
      { key: 'fontFamily',     type: 'select',  label: 'Font',                default: 'Orbitron', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Orbitron','Audiowide','Rajdhani'] },
      { key: 'fontSizePx',     type: 'number',  label: 'Font size (px)',      default: 64 },
      { key: 'textColor',      type: 'color',   label: 'Text colour',         default: '#ffffff' },
      { key: 'accentColor',    type: 'color',   label: 'Accent colour',       default: '#6366f1' },
      { key: 'bgColor',        type: 'color',   label: 'Background',          default: 'transparent' },
      { key: 'showProgressBar',type: 'boolean', label: 'Show progress bar',   default: true },
      { key: 'showLastEvent',  type: 'boolean', label: 'Show last event',     default: true },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});
