// src/widgets/allWidgets.ts
// Registers all overlay widgets in the WIDGET_REGISTRY.
// Import this from the overlay editor and runtime entry points.

import { registerWidget } from '../shared/widgetRegistry.js';
import { GOOGLE_FONTS } from '../shared/FontManager.js';

// Font options for widget config schemas
const FONT_OPTIONS = GOOGLE_FONTS;

registerWidget({
  id: 'chat-overlay',
  name: 'Chat Overlay',
  schemaVersion: 2,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'chat-overlay',
    category:    'display',
    version:     '2.0.0',
    displayName: 'Chat Overlay',
    description: 'Displays live chat messages from Kick, YouTube, and Twitch. Fully customisable with bubble styles, avatars, and platform icons.',
    icon:        'monitor',
    dataContract: {
      sseEventType: 'chat_message',
      fields: [
        { key: 'username', label: 'Username',     type: 'string', fallback: '' },
        { key: 'message',  label: 'Message',      type: 'string', fallback: '' },
        { key: 'platform', label: 'Platform',     type: 'string', fallback: 'kick' },
        { key: 'avatar',   label: 'Avatar URL',   type: 'string', fallback: '' },
        { key: 'color',    label: 'Name Colour',  type: 'string', fallback: '' },
      ],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/chat-overlay.js',
    configSchema: [
      // Typography
      { key: 'fontFamily', type: 'select', label: 'Font', default: 'Inter', options: FONT_OPTIONS },
      { key: 'fontSizePx',      type: 'number',  label: 'Font size (px)',        default: 16 },
      { key: 'lineHeight',      type: 'number',  label: 'Line height',           default: 1.4 },
      { key: 'messageGapPx',    type: 'number',  label: 'Gap between messages (px)', default: 6 },
      // Colours
      { key: 'nameColorMode', type: 'select', label: 'Name colour mode', default: 'custom', options: ['custom', 'platform', 'user'] },
      { key: 'nameColor', type: 'color', label: 'Name colour (custom)', default: '#a5b4fc', showWhen: { key: 'nameColorMode', value: 'custom' } },
      { key: 'messageColor',    type: 'color',   label: 'Message colour',        default: '#ffffff' },
      // Display options
      { key: 'showAvatars',     type: 'boolean', label: 'Show avatars',          default: false },
      { key: 'showBadges',      type: 'boolean', label: 'Show badges',           default: true },
      { key: 'gradientNames',   type: 'boolean', label: 'Gradient name colours', default: false },
      { key: 'showPlatformIcon',type: 'boolean', label: 'Show platform icon',    default: true },
      { key: 'shadow',          type: 'boolean', label: 'Text shadow',           default: true },
      { key: 'animateIn',       type: 'boolean', label: 'Animate messages in',   default: true },
      { key: 'stripEmotes',     type: 'boolean', label: 'Strip emote codes',      default: false },
      // Bubble style
      { key: 'bubbleEnabled',   type: 'boolean', label: 'Message bubbles',       default: false },
      { key: 'bubbleRadiusPx',  type: 'number',  label: 'Bubble corner radius',  default: 8 },
      { key: 'bubbleBg',        type: 'color',   label: 'Bubble background',     default: 'rgba(0,0,0,0.4)' },
      { key: 'bubbleBorder',    type: 'color',   label: 'Bubble border',         default: 'transparent' },
      // Limits
      { key: 'limitsMaxMessages', type: 'number', label: 'Max messages shown',   default: 20 },
      { key: 'limitsFadeMs',    type: 'number',  label: 'Fade out after (ms, 0=never)', default: 0 },
      { key: 'fadeTop',         type: 'boolean', label: 'Fade at top edge',      default: true },
      { key: 'fadeTopHeight',   type: 'number',  label: 'Fade height (px)',      default: 60 },
      // Visual effects
      { key: 'glowEnabled',     type: 'boolean', label: 'Name glow effect',      default: false },
      { key: 'glowColor',       type: 'color',   label: 'Glow colour',           default: '#a5b4fc' },
      { key: 'glowBlur',        type: 'number',  label: 'Glow blur (px)',        default: 8 },
      { key: 'depthEnabled',    type: 'boolean', label: 'Depth/3D effect',       default: false },
      { key: 'depthOffset',     type: 'number',  label: 'Depth offset (px)',     default: 2 },
      { key: 'depthColor',      type: 'color',   label: 'Depth colour',          default: 'rgba(0,0,0,0.5)' },
      // Platform filters
      { key: 'enableKick',      type: 'boolean', label: 'Show Kick chat',        default: true },
      { key: 'enableYoutube',   type: 'boolean', label: 'Show YouTube chat',     default: true },
      { key: 'enableTwitch',    type: 'boolean', label: 'Show Twitch chat',      default: true },
      // Content filters (Task 10)
      { key: 'filterCommands',  type: 'boolean', label: 'Hide ! commands',       default: false },
      { key: 'emoteOnly',       type: 'boolean', label: 'Emote-only mode',       default: false },
      { key: 'minTrustScore',   type: 'number',  label: 'Min trust score (0-100)', default: 0 },
      { key: 'keywordHighlightColor', type: 'color', label: 'Keyword highlight colour', default: '#fbbf24' },
      { key: 'keywordHighlights', type: 'text',  label: 'Highlight keywords (comma-separated)', default: '' },
    ],
    defaultProps: {
      token: '',
      fontFamily: 'Inter, system-ui, sans-serif',
      fontSizePx: 16, lineHeight: 1.4, messageGapPx: 6,
      nameColor: '#a5b4fc', messageColor: '#ffffff',
      showAvatars: false, showPlatformIcon: true, shadow: true, animateIn: true,
      bubbleEnabled: false, bubbleRadiusPx: 8, bubbleBg: 'rgba(0,0,0,0.4)', bubbleBorder: 'transparent',
      limitsMaxMessages: 20, limitsFadeMs: 0, fadeTop: true, fadeTopHeight: 60,
      enableKick: true, enableYoutube: true, enableTwitch: true,
    },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'alert-box-widget',
  name: 'Alert Box',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'alert-box-widget',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Alert Box',
    description: 'Shows animated alerts for follows, subs, donations, and raids.',
    icon:        'monitor',
    dataContract: {
      sseEventType: 'follow',
      fields: [
        { key: 'username', label: 'Username', type: 'string', fallback: '' },
        { key: 'message',  label: 'Message',  type: 'string', fallback: '' },
        { key: 'type',     label: 'Event Type', type: 'string', fallback: '' },
      ],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/alert-box-widget.js',
    configSchema: [
      // Global
      { key: 'fontFamily',    type: 'select', label: 'Font', default: 'Inter', options: FONT_OPTIONS },
      { key: 'fontSizePx',    type: 'number', label: 'Font size (px)', default: 20 },
      { key: 'textColor',     type: 'color',  label: 'Text colour',    default: '#ffffff' },
      { key: 'masterVolume',  type: 'number', label: 'Master volume',  default: 0.8 },
      // Per-event config — rendered by alertConfig inspector
      { key: 'alertTypes', type: 'alertConfig', label: 'Alert Events', default: {} },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'sub-counter',
  name: 'Sub Counter',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'sub-counter',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Sub Counter',
    description: 'Shows subscriber count with an optional goal progress bar.',
    icon:        'monitor',
    dataContract: {
      sseEventType: 'subs.update',
      fields: [],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/sub-counter.js',
    configSchema: [
      // Display
      { key: 'displayMode',   type: 'select',  label: 'Display mode',      default: 'bar',   options: ['bar','ring','counter'] },
      { key: 'label',         type: 'text',    label: 'Label',             default: 'Sub Goal' },
      { key: 'fontFamily',    type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',    type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'textColor',     type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'fillColor',     type: 'color',   label: 'Bar fill colour',   default: '#6366f1' },
      { key: 'fillColor2',    type: 'color',   label: 'Bar fill gradient', default: '' },
      { key: 'trackColor',    type: 'color',   label: 'Bar track colour',  default: 'rgba(255,255,255,0.1)' },
      { key: 'bgColor',       type: 'color',   label: 'Background',        default: 'transparent' },
      // Goal
      { key: 'goal',          type: 'number',  label: 'Goal',              default: 100 },
      { key: 'startAt',       type: 'number',  label: 'Starting count',    default: 0 },
      { key: 'overfill',      type: 'boolean', label: 'Overfill bar',      default: true },
      { key: 'trackPoints',   type: 'boolean', label: 'Track sub points (tier-weighted)', default: false },
      { key: 'endDate',       type: 'text',    label: 'End date (ISO)',    default: '' },
      // Numbers
      { key: 'showNumbers',   type: 'boolean', label: 'Show numbers',      default: true },
      { key: 'showPercent',   type: 'boolean', label: 'Show percentage',   default: false },
      { key: 'showBreakdown', type: 'boolean', label: 'Show platform breakdown', default: false },
      // Milestone
      { key: 'milestoneAnim', type: 'select',  label: 'Milestone animation', default: 'pulse', options: ['pulse','shake','confetti','none'] },
      { key: 'milestoneSound', type: 'audio',  label: 'Milestone sound', default: '' },
      // Text effects
      { key: 'textShadow',    type: 'boolean', label: 'Text shadow',        default: false },
      { key: 'textGlow',      type: 'boolean', label: 'Text glow',          default: false },
      { key: 'glowColor',     type: 'color',   label: 'Glow colour',        default: '#6366f1' },
      { key: 'glowBlur',      type: 'number',  label: 'Glow blur (px)',     default: 8 },
      // Border
      { key: 'borderEnabled', type: 'boolean', label: 'Border',             default: false },
      { key: 'borderWidth',   type: 'number',  label: 'Border width (px)',  default: 2 },
      { key: 'borderColor',   type: 'color',   label: 'Border colour',      default: '#6366f1' },
      { key: 'borderRadius',  type: 'number',  label: 'Container radius (px)', default: 12 },
      // Bar style
      { key: 'barHeight',     type: 'number',  label: 'Bar height (px)',   default: 12, showWhen: { key: 'displayMode', value: 'bar' } },
      { key: 'barRadius',     type: 'number',  label: 'Bar corner radius', default: 999, showWhen: { key: 'displayMode', value: 'bar' } },
      { key: 'barOrientation',type: 'select',  label: 'Orientation',       default: 'horizontal', options: ['horizontal','vertical'], showWhen: { key: 'displayMode', value: 'bar' } },
      { key: 'barGlow',       type: 'boolean', label: 'Bar glow effect',   default: false, showWhen: { key: 'displayMode', value: 'bar' } },
      { key: 'barBorderEnabled', type: 'boolean', label: 'Bar border',     default: false, showWhen: { key: 'displayMode', value: 'bar' } },
      { key: 'barBorderWidth',   type: 'number',  label: 'Bar border width (px)', default: 2, showWhen: { key: 'displayMode', value: 'bar' } },
      { key: 'barBorderColor',   type: 'color',   label: 'Bar border colour',     default: '#6366f1', showWhen: { key: 'displayMode', value: 'bar' } },
      // Ring style
      { key: 'ringSize',      type: 'number',  label: 'Ring size (px)',    default: 120, showWhen: { key: 'displayMode', value: 'ring' } },
      { key: 'ringStroke',    type: 'number',  label: 'Ring stroke width', default: 10,  showWhen: { key: 'displayMode', value: 'ring' } },
      { key: 'ringGlow',      type: 'boolean', label: 'Ring glow effect',  default: false, showWhen: { key: 'displayMode', value: 'ring' } },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'poll',
  name: 'Poll',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'poll',
    category:    'interactive',
    version:     '1.0.0',
    displayName: 'Poll',
    description: 'Live poll with animated vote bars. Syncs with Kick native polls. Viewers vote via chat.',
    icon:        'monitor',
    dataContract: { sseEventType: 'poll.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/poll.js',
    configSchema: [
      { key: 'showTitle',       type: 'boolean', label: 'Show title',          default: true },
      { key: 'showVoteCount',   type: 'boolean', label: 'Show vote count',     default: true },
      { key: 'showPercent',     type: 'boolean', label: 'Show percentage',     default: true },
      { key: 'showTimer',       type: 'boolean', label: 'Show timer',          default: true },
      { key: 'showWinner',      type: 'boolean', label: 'Show winner banner',  default: true },
      { key: 'animateBars',     type: 'boolean', label: 'Animate bars',        default: true },
      { key: 'highlightWinner', type: 'boolean', label: 'Highlight winner',    default: true },
      { key: 'voteCommand',     type: 'text',    label: 'Vote command',        default: '!vote' },
      { key: 'fontFamily',      type: 'select',  label: 'Font',                default: 'Inter', options: FONT_OPTIONS },
      { key: 'fontSizePx',      type: 'number',  label: 'Font size (px)',      default: 15 },
      { key: 'barHeight',       type: 'number',  label: 'Bar height (px)',     default: 32 },
      { key: 'barRadius',       type: 'number',  label: 'Bar radius (px)',     default: 6 },
      { key: 'textColor',       type: 'color',   label: 'Text colour',         default: '#ffffff' },
      { key: 'bgColor',         type: 'color',   label: 'Background',          default: 'rgba(0,0,0,0.8)' },
      { key: 'barBg',           type: 'color',   label: 'Bar background',      default: 'rgba(255,255,255,0.1)' },
      { key: 'accentColor',     type: 'color',   label: 'Accent colour',       default: '#6366f1' },
      { key: 'winnerColor',     type: 'color',   label: 'Winner colour',       default: '#fbbf24' },
      { key: 'borderRadius',    type: 'number',  label: 'Border radius (px)',  default: 12 },
      { key: 'color1',          type: 'color',   label: 'Option 1 colour',     default: '#6366f1' },
      { key: 'color2',          type: 'color',   label: 'Option 2 colour',     default: '#ec4899' },
      { key: 'color3',          type: 'color',   label: 'Option 3 colour',     default: '#10b981' },
      { key: 'color4',          type: 'color',   label: 'Option 4 colour',     default: '#f59e0b' },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'countdown',
  name: 'Countdown',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'countdown',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Countdown',
    description: 'Counts down to a fixed date/time or a set duration. Perfect for stream start, events, or breaks.',
    icon:        'monitor',
    dataContract: { sseEventType: null, fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/countdown.js',
    configSchema: [
      { key: 'mode',          type: 'select',  label: 'Mode',                default: 'datetime', options: ['datetime','duration'] },
      { key: 'targetDate',    type: 'text',    label: 'Target date/time (ISO)', default: '', showWhen: { key: 'mode', value: 'datetime' } },
      { key: 'durationSec',   type: 'number',  label: 'Duration (seconds)',  default: 3600, showWhen: { key: 'mode', value: 'duration' } },
      { key: 'layout',        type: 'select',  label: 'Layout',              default: 'blocks', options: ['blocks','inline'] },
      { key: 'label',         type: 'text',    label: 'Label',               default: 'STREAM STARTS IN' },
      { key: 'showLabel',     type: 'boolean', label: 'Show label',          default: true },
      { key: 'showDays',      type: 'boolean', label: 'Show days',           default: true },
      { key: 'showHours',     type: 'boolean', label: 'Show hours',          default: true },
      { key: 'showMinutes',   type: 'boolean', label: 'Show minutes',        default: true },
      { key: 'showSeconds',   type: 'boolean', label: 'Show seconds',        default: true },
      { key: 'showUnits',     type: 'boolean', label: 'Show unit labels',    default: true },
      { key: 'showBar',       type: 'boolean', label: 'Show progress bar',   default: false },
      { key: 'separatorChar', type: 'text',    label: 'Separator',           default: ':' },
      { key: 'endMessage',    type: 'text',    label: 'End message',         default: 'LIVE NOW! 🔴' },
      { key: 'showEndMsg',    type: 'boolean', label: 'Show end message',    default: true },
      { key: 'urgentSec',     type: 'number',  label: 'Urgent threshold (s)', default: 60 },
      { key: 'fontFamily',    type: 'select',  label: 'Font',                default: 'Inter', options: FONT_OPTIONS },
      { key: 'fontSizePx',    type: 'number',  label: 'Number size (px)',    default: 48 },
      { key: 'labelSizePx',   type: 'number',  label: 'Label size (px)',     default: 13 },
      { key: 'textColor',     type: 'color',   label: 'Text colour',         default: '#ffffff' },
      { key: 'bgColor',       type: 'color',   label: 'Background',          default: 'transparent' },
      { key: 'blockBg',       type: 'color',   label: 'Block background',    default: 'rgba(0,0,0,0.4)' },
      { key: 'accentColor',   type: 'color',   label: 'Accent colour',       default: '#6366f1' },
      { key: 'urgentColor',   type: 'color',   label: 'Urgent colour',       default: '#ef4444' },
      { key: 'borderRadius',  type: 'number',  label: 'Border radius (px)',  default: 10 },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'top-supporters',
  name: 'Top Supporters',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'top-supporters',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Top Supporters',
    description: 'Live leaderboard of top subscribers, donors, and supporters across all platforms.',
    icon:        'monitor',
    dataContract: { sseEventType: 'channel.subscription.new', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/top-supporters.js',
    configSchema: [
      { key: 'title',         type: 'text',    label: 'Title',             default: 'Top Supporters' },
      { key: 'showTitle',     type: 'boolean', label: 'Show title',        default: true },
      { key: 'maxEntries',    type: 'number',  label: 'Max entries',       default: 5 },
      { key: 'metric',        type: 'select',  label: 'Rank by',           default: 'combined', options: ['subs','tips','combined'] },
      { key: 'timePeriod',    type: 'select',  label: 'Time period',       default: 'session',  options: ['session','today','week','month','alltime'] },
      { key: 'layout',        type: 'select',  label: 'Layout',            default: 'list',     options: ['list','podium'] },
      { key: 'showRank',      type: 'boolean', label: 'Show rank/medals',  default: true },
      { key: 'showAmount',    type: 'boolean', label: 'Show amount',       default: true },
      { key: 'showPlatform',  type: 'boolean', label: 'Show platform icon',default: true },
      { key: 'highlightTop',  type: 'boolean', label: 'Highlight #1',      default: true },
      { key: 'fontFamily',    type: 'select',  label: 'Font',              default: 'Inter', options: FONT_OPTIONS },
      { key: 'fontSizePx',    type: 'number',  label: 'Font size (px)',    default: 15 },
      { key: 'textColor',     type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'bgColor',       type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.6)' },
      { key: 'accentColor',   type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'goldColor',     type: 'color',   label: '#1 highlight colour',default: '#fbbf24' },
      { key: 'rowBg',         type: 'color',   label: 'Row background',    default: 'rgba(255,255,255,0.04)' },
      { key: 'borderRadius',  type: 'number',  label: 'Border radius (px)', default: 10 },
      { key: 'rowGap',        type: 'number',  label: 'Row gap (px)',      default: 4 },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'media-queue',
  name: 'Media Request Queue',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'media-queue',
    category:    'interactive',
    version:     '1.0.0',
    displayName: 'Media Request Queue',
    description: 'Shows the current song/video request queue. Viewers request via chat command.',
    icon:        'monitor',
    dataContract: { sseEventType: 'queue.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/media-queue.js',
    configSchema: [
      // Display
      { key: 'showNowPlaying', type: 'boolean', label: 'Show now playing',  default: true },
      { key: 'showQueue',      type: 'boolean', label: 'Show queue',        default: true },
      { key: 'maxVisible',     type: 'number',  label: 'Max queue entries', default: 5 },
      { key: 'showRequester',  type: 'boolean', label: 'Show requester',    default: true },
      { key: 'showVotes',      type: 'boolean', label: 'Show votes',        default: true },
      { key: 'showPlatform',   type: 'boolean', label: 'Show platform icon',default: true },
      { key: 'showCommand',    type: 'boolean', label: 'Show command hint', default: true },
      // Labels
      { key: 'command',        type: 'text',    label: 'Request command',   default: '!sr' },
      { key: 'nowPlayingLabel',type: 'text',    label: 'Now playing label', default: 'NOW PLAYING' },
      { key: 'upNextLabel',    type: 'text',    label: 'Up next label',     default: 'UP NEXT' },
      { key: 'emptyLabel',     type: 'text',    label: 'Empty queue text',  default: 'Queue is empty — use !sr to request!' },
      // Typography
      { key: 'fontFamily',     type: 'select',  label: 'Font',              default: 'Inter', options: FONT_OPTIONS },
      { key: 'fontSizePx',     type: 'number',  label: 'Font size (px)',    default: 14 },
      // Colours
      { key: 'textColor',      type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'bgColor',        type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.75)' },
      { key: 'nowPlayingBg',   type: 'color',   label: 'Now playing bg',    default: 'rgba(99,102,241,0.2)' },
      { key: 'nowPlayingColor',type: 'color',   label: 'Now playing accent',default: '#a5b4fc' },
      { key: 'rowBg',          type: 'color',   label: 'Row background',    default: 'rgba(255,255,255,0.04)' },
      { key: 'accentColor',    type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'borderRadius',   type: 'number',  label: 'Border radius (px)', default: 10 },
      { key: 'rowGap',         type: 'number',  label: 'Row gap (px)',      default: 3 },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'viewer-count',
  name: 'Viewer Count',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'viewer-count',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Viewer Count',
    description: 'Live viewer count with per-platform breakdown across Kick, YouTube, and Twitch.',
    icon:        'monitor',
    dataContract: { sseEventType: 'viewer.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/viewer-count.js',
    configSchema: [
      // Display
      { key: 'displayMode',   type: 'select',  label: 'Display mode',      default: 'both',     options: ['total','breakdown','both'] },
      { key: 'layout',        type: 'select',  label: 'Layout',            default: 'vertical', options: ['vertical','horizontal','compact'] },
      { key: 'label',         type: 'text',    label: 'Label',             default: 'VIEWERS' },
      { key: 'showLabel',     type: 'boolean', label: 'Show label',        default: true },
      { key: 'showIcon',      type: 'boolean', label: 'Show eye icon',     default: true },
      { key: 'showPeak',      type: 'boolean', label: 'Show peak viewers', default: false },
      // Platform toggles
      { key: 'showKick',      type: 'boolean', label: 'Show Kick',         default: true },
      { key: 'showYoutube',   type: 'boolean', label: 'Show YouTube',      default: true },
      { key: 'showTwitch',    type: 'boolean', label: 'Show Twitch',       default: true },
      // Typography
      { key: 'fontFamily',    type: 'select',  label: 'Font',              default: 'Inter', options: FONT_OPTIONS },
      { key: 'fontSizePx',    type: 'number',  label: 'Count font size (px)', default: 48 },
      { key: 'labelSizePx',   type: 'number',  label: 'Label font size (px)', default: 12 },
      // Colours
      { key: 'textColor',     type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'bgColor',       type: 'color',   label: 'Background',        default: 'transparent' },
      { key: 'accentColor',   type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      // Border
      { key: 'borderEnabled', type: 'boolean', label: 'Border',            default: false },
      { key: 'borderWidth',   type: 'number',  label: 'Border width (px)', default: 2 },
      { key: 'borderColor',   type: 'color',   label: 'Border colour',     default: '#6366f1' },
      { key: 'borderRadius',  type: 'number',  label: 'Border radius (px)', default: 12 },
      // Animation
      { key: 'animateCount',  type: 'boolean', label: 'Animate count changes', default: true },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'ticker',
  name: 'Scrolling Ticker',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'ticker',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Scrolling Ticker',
    description: 'Horizontal scrolling marquee for announcements, sponsors, social handles, and custom messages.',
    icon:        'monitor',
    dataContract: { sseEventType: null, fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/ticker.js',
    configSchema: [
      // Content
      { key: 'items',         type: 'text',    label: 'Items (one per line or | separated)', default: 'Welcome to the stream!\nFollow for more content\nCheck the links below' },
      { key: 'separator',     type: 'text',    label: 'Separator',         default: ' • ' },
      { key: 'prefixLabel',   type: 'text',    label: 'Prefix label (e.g. LIVE)', default: '' },
      { key: 'prefixIcon',    type: 'text',    label: 'Prefix icon (emoji)', default: '📢' },
      // Typography
      { key: 'fontFamily',    type: 'select',  label: 'Font',              default: 'Inter', options: FONT_OPTIONS },
      { key: 'fontSizePx',    type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'bold',          type: 'boolean', label: 'Bold text',         default: false },
      { key: 'uppercase',     type: 'boolean', label: 'Uppercase',         default: false },
      { key: 'letterSpacing', type: 'number',  label: 'Letter spacing (px)', default: 0 },
      { key: 'textShadow',    type: 'boolean', label: 'Text shadow',       default: false },
      // Colours
      { key: 'textColor',     type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'bgColor',       type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.6)' },
      { key: 'accentColor',   type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      // Motion
      { key: 'speed',         type: 'number',  label: 'Speed (px/sec)',    default: 60 },
      { key: 'direction',     type: 'select',  label: 'Direction',         default: 'left', options: ['left','right'] },
      { key: 'pauseOnHover',  type: 'boolean', label: 'Pause on hover',    default: false },
      // Style
      { key: 'showAccent',    type: 'boolean', label: 'Show accent bar',   default: true },
      { key: 'accentWidth',   type: 'number',  label: 'Accent bar width (px)', default: 4 },
      { key: 'fadeEdges',     type: 'boolean', label: 'Fade edges',        default: true },
      { key: 'fadeWidth',     type: 'number',  label: 'Fade width (px)',   default: 60 },
      { key: 'paddingV',      type: 'number',  label: 'Vertical padding (px)', default: 10 },
      { key: 'paddingH',      type: 'number',  label: 'Horizontal padding (px)', default: 16 },
      { key: 'borderRadius',  type: 'number',  label: 'Border radius (px)', default: 8 },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'event-console-widget',
  name: 'Event Console',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'event-console-widget',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Event Console',
    description: 'Shows a scrolling log of stream events — follows, subs, donations, chat.',
    icon:        'monitor',
    dataContract: {
      sseEventType: 'follow',
      fields: [
        { key: 'username', label: 'Username', type: 'string', fallback: '' },
        { key: 'message',  label: 'Message',  type: 'string', fallback: '' },
        { key: 'type',     label: 'Event Type', type: 'string', fallback: '' },
      ],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/event-console-widget.js',
    configSchema: [
      { key: 'newestTop',     type: 'boolean', label: 'Newest at top',        default: true },
      { key: 'maxEvents',     type: 'number',  label: 'Max events shown',     default: 12 },
      { key: 'expireSec',     type: 'number',  label: 'Auto-expire after (s, 0=never)', default: 0 },
      { key: 'entryAnim',     type: 'select',  label: 'Entry animation',      default: 'slide-left', options: ['slide-left','slide-right','fade','scale'] },
      { key: 'fontFamily',    type: 'select',  label: 'Font',                 default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',    type: 'number',  label: 'Font size (px)',       default: 14 },
      { key: 'textColor',     type: 'color',   label: 'Text colour',          default: '#e2e8f0' },
      { key: 'rowBg',         type: 'color',   label: 'Row background',       default: 'rgba(0,0,0,0.4)' },
      { key: 'rowBgAlt',      type: 'color',   label: 'Alternating row bg',   default: '' },
      { key: 'containerBg',   type: 'color',   label: 'Container background', default: 'transparent' },
      { key: 'borderRadius',  type: 'number',  label: 'Border radius (px)',   default: 8 },
      { key: 'rowPadding',    type: 'number',  label: 'Row padding (px)',     default: 6 },
      { key: 'accentWidth',   type: 'number',  label: 'Accent bar width (px)',default: 3 },
      { key: 'showTimestamp', type: 'boolean', label: 'Show timestamp',       default: false },
      { key: 'showAvatar',    type: 'boolean', label: 'Show avatars',         default: false },
      { key: 'showPlatform',  type: 'boolean', label: 'Show platform icon',   default: true },
      { key: 'eventTypes',    type: 'alertConfig', label: 'Event Types',      default: {} },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'raffle',
  name: 'Raffle',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'raffle',
    category:    'interactive',
    version:     '1.0.0',
    displayName: 'Raffle',
    description: 'Live raffle widget — viewers enter via chat command, winner drawn on screen.',
    icon:        'monitor',
    dataContract: {
      sseEventType: 'raffle_update',
      fields: [
        { key: 'username', label: 'Username', type: 'string', fallback: '' },
        { key: 'message',  label: 'Message',  type: 'string', fallback: '' },
        { key: 'type',     label: 'Event Type', type: 'string', fallback: '' },
      ],
    },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/raffle.js',
    configSchema: [
      // Visual
      { key: 'fontFamily',   type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',   type: 'number',  label: 'Font size (px)',    default: 18 },
      { key: 'textColor',    type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor',  type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'winnerColor',  type: 'color',   label: 'Winner colour',     default: '#fbbf24' },
      { key: 'bgColor',      type: 'color',   label: 'Background',        default: 'rgba(0,0,0,0.85)' },
      { key: 'borderRadius', type: 'number',  label: 'Border radius (px)',default: 16 },
      // Animation preference (empty = use server value)
      { key: 'prefAnim',     type: 'select',  label: 'Animation override',default: '', options: ['','wheel','slot','scramble'] },
      // Toggles
      { key: 'showStatus',   type: 'boolean', label: 'Show status dot',   default: true },
      { key: 'showCount',    type: 'boolean', label: 'Show entry count',  default: true },
      { key: 'showJoinCmd',  type: 'boolean', label: 'Show join command', default: true },
      { key: 'joinCommand',  type: 'text',    label: 'Join command',      default: '!join' },
      { key: 'autoDismissSec', type: 'number',  label: 'Auto-dismiss after winner (s, 0=never)', default: 10 },
      { key: 'subWeight',      type: 'number',  label: 'Subscriber entry weight (1=normal, 2=double chance)', default: 1 },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

// cache bust

registerWidget({
  id: 'hype-train',
  name: 'Hype Train',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'hype-train',
    category:    'interactive',
    version:     '1.0.0',
    displayName: 'Hype Train',
    description: 'Animated SVG train that levels up as viewers subscribe, tip, and donate. Gets increasingly chaotic at higher levels.',
    icon:        'monitor',
    dataContract: { sseEventType: 'hype.update', fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/hype-train.js',
    configSchema: [
      // Behaviour
      { key: 'difficulty',        type: 'select',  label: 'Difficulty',              default: 'easy',    options: ['easy','alright','hard','insane'] },
      { key: 'time_per_contrib_sec', type: 'number', label: 'Timer per contribution (s)', default: 30 },
      { key: 'tip_pts_per_unit',  type: 'number',  label: 'Tip $ per point',         default: 5 },
      { key: 'narrate',           type: 'boolean', label: 'Scrapbot narration',       default: true },
      // Display
      { key: 'showConductor',     type: 'boolean', label: 'Show conductor',          default: true },
      { key: 'showLevel',         type: 'boolean', label: 'Show level',              default: true },
      { key: 'showTimer',         type: 'boolean', label: 'Show timer',              default: true },
      { key: 'showBar',           type: 'boolean', label: 'Show progress bar',       default: true },
      // Colours
      { key: 'trainColor',        type: 'color',   label: 'Train colour',            default: '#6366f1' },
      { key: 'trainColor2',       type: 'color',   label: 'Train accent',            default: '#4f46e5' },
      { key: 'wheelColor',        type: 'color',   label: 'Wheel colour',            default: '#1e1b4b' },
      { key: 'barColor',          type: 'color',   label: 'Bar colour',              default: '#6366f1' },
      { key: 'textColor',         type: 'color',   label: 'Text colour',             default: '#ffffff' },
      // Typography
      { key: 'fontFamily',        type: 'select',  label: 'Font',                    default: 'Inter', options: FONT_OPTIONS },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});

registerWidget({
  id: 'subathon-timer',
  name: 'Subathon Timer',
  schemaVersion: 1,
  propsSchema: {},
  metadata: {},
  widgetManifest: {
    widgetId:    'subathon-timer',
    category:    'display',
    version:     '1.0.0',
    displayName: 'Subathon Timer',
    description: 'Countdown timer that extends when viewers subscribe, follow, or tip. Control from the dashboard.',
    icon:        'monitor',
    dataContract: { sseEventType: null, fields: [] },
    beaconEndpoint: null,
    invisible:      false,
    runtimeScript:  '/widgets/subathon-timer.js',
    configSchema: [
      { key: 'label',       type: 'text',    label: 'Label text',        default: 'SUBATHON' },
      { key: 'fontFamily',  type: 'select',  label: 'Font',              default: 'Inter', options: ['Inter','Roboto','Open Sans','Oswald','Bebas Neue','Montserrat','Rajdhani','Exo 2','Barlow','Nunito','Poppins','Lato','Space Grotesk','DM Sans'] },
      { key: 'fontSizePx',  type: 'number',  label: 'Clock font size',   default: 48 },
      { key: 'textColor',   type: 'color',   label: 'Text colour',       default: '#ffffff' },
      { key: 'accentColor', type: 'color',   label: 'Accent colour',     default: '#6366f1' },
      { key: 'bgColor',     type: 'color',   label: 'Background',        default: 'transparent' },
      { key: 'showLabel',   type: 'boolean', label: 'Show label',        default: true },
      { key: 'showBar',     type: 'boolean', label: 'Show progress bar', default: true },
      { key: 'showAddAnim', type: 'boolean', label: 'Show +time animation', default: true },
      { key: 'urgentMs',    type: 'number',  label: 'Urgent threshold (ms)', default: 300000 },
    ],
    defaultProps: { token: '' },
    previewImageUrl: null,
  },
});


